AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless lambda using a pandoc lambda layer to convert .docx documents
  into .pdf

  This lambda requires a pandoc biniary as a lambda layer

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: app.lambda_handler
      CodeUri: src/
      Runtime: python3.7
    Policies:
      - Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Resource: 'arn:aws:s3:::*'
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pandoc-lambda-layer
      Description: pandoc binary built to run on AWS Lambda. Built From https://github.com/ministryofjustice/alchemy
      ContentUri: s3://alchemy.service.justice.gov.uk/pandoc_binary.zip
      CompatibleRuntimes:
        - python3.7

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  LayerArn:
    Value: !Ref SharedLayer
