version: 2.1

workflows:
  path_to_live:
    jobs:
      - alchemy-build/fetch-pandoc
      - alchemy-build/build_sam

orbs:
  alchemy-build:
    commands:
      install_sam_cli:
        steps:
          - run:
              name: Install SAM CLI
              command: sudo pip3 install aws-sam-cli --upgrade
    executors:
      python:
        docker: [image: circleci/python]
      lamci:
        docker: [image: lambci/lambda-base-2:build]

    jobs:
      fetch-pandoc:
        executor: python
        steps:
          - run:
              name: curl pandoc from github
              command: |
                curl -s https://api.github.com/repos/jgm/pandoc/releases/latest \
                | grep "browser_download_url.*tar.gz" \
                | cut -d : -f 2,3 \
                | tr -d \" \
                | wget -qi -

                tar xvzf pandoc-*.tar.gz
                zip -r pandoc_binary.zip pandoc-*/bin/pandoc
                ls -al
      build_sam:
        executor: python
        steps:
          - checkout
          - install_sam_cli
          - setup_remote_docker:
              version: 18.06.0-ce
              docker_layer_caching: false
          - run:
              name:
              command: |
                sam build
