version: 2.1

workflows:
  path_to_live:
    jobs:
      - fetch-pandoc:
          name: fetch_pandoc
      - build_sam:
          name: build_sam
          requires: [fetch_pandoc]

orbs:
  aws-s3: circleci/aws-s3@1.0.11

  alchemy-build:
    commands:
      install_sam_cli:
        steps:
          - run:
              name: Install SAM CLI
              command: sudo pip3 install aws-sam-cli --upgrade
    executors:
      python:
        docker: [image: circleci/python]

jobs:
  fetch-pandoc:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - run:
          name: curl pandoc from github
          command: |
            curl -s https://api.github.com/repos/jgm/pandoc/releases/latest \
            | grep "browser_download_url.*tar.gz" \
            | cut -d : -f 2,3 \
            | tr -d \" \
            | wget -qi -

            tar xvzf pandoc-*.tar.gz
            zip -r pandoc_binary.zip pandoc-*/bin/pandoc
            ls -al
      - aws-s3/copy:
          from: pandoc_binary.zip
          to: 's3://alchemy.service.justice.gov.uk'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  build_sam:
    executor: alchemy-build/python
    steps:
      - checkout
      - alchemy-build/install_sam_cli
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: false
      - run:
          name:
          command: |
            sam build
