version: 2.1

workflows:
  path_to_live:
    jobs:
      - fetch-pandoc:
          name: fetch_pandoc
      - build_sam:
          name: build_sam
          requires: [fetch_pandoc]

orbs:
  aws-cli: circleci/aws-cli@0.1.13
  alchemy-build:
    commands:
      install_sam_cli:
        steps:
          - run:
              name: Install SAM CLI
              command: sudo pip3 install aws-sam-cli --upgrade
    executors:
      python:
        docker: [image: circleci/python]

jobs:
  fetch-pandoc:
    docker:
      - image: 'circleci/python:2.7'
    environment:
      AWS_REGION: eu-west-1
      AWS_SHARED_CREDENTIALS_FILE: ~/project/credentials
    steps:
      - aws-cli/install
      - checkout
      - run:
          name: get latest pandoc
          command: |
            curl -s https://api.github.com/repos/jgm/pandoc/releases/latest \
            | grep "browser_download_url.*tar.gz" \
            | cut -d : -f 2,3 \
            | tr -d \" \
            | wget -qi -
      - run:
          name: extract pandoc
          command: tar xvzf pandoc-*.tar.gz
      - run:
          name: zip pandoc
          command: zip -r pandoc_binary.zip pandoc-*/bin/pandoc
      - run:
          name: copy pandoc to s3
          command: aws s3 cp pandoc_binary.zip s3://alchemy.service.justice.gov.uk/ --profile alchemy-ci
  build_sam:
    executor: alchemy-build/python
    steps:
      - checkout
      - alchemy-build/install_sam_cli
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: false
      - run:
          name:
          command: |
            sam build
